const moduleRoom = {
  state: () => ({
    roomList: [
      {
        id: 1,
        name: "Biệt thự Vườn Xanh",
        guest: 8,
        bedRoom: 4,
        bath: 4,
        description:
          "Biệt thự sang trọng với vườn xanh mát, phòng ngủ rộng rãi và đầy đủ tiện nghi.",
        price: "500 000 VND",
        elevator: false,
        hotTub: true,
        pool: true,
        indoorFireplace: true,
        dryer: true,
        gym: false,
        kitchen: true,
        wifi: true,
        heating: true,
        cableTV: true,
        location: {
          id: 2,
          name: "Hạ Long",
          province: "Quảng Ninh",
          country: "Việt Nam",
        },
        image:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbMwKbIezzGGAk8cUr6jHmAp2HSrnKPQetjQ&usqp=CAU",
      },
      {
        id: 2,
        name: "Căn hộ Sóng Sánh Biển",
        guest: 4,
        bedRoom: 2,
        bath: 2,
        description:
          "Căn hộ hiện đại nằm ngay bên bờ biển, với không gian thoáng đãng và tiện nghi đẳng cấp.",
        price: "1 000 000 VND",
        elevator: true,
        hotTub: false,
        pool: true,
        indoorFireplace: false,
        dryer: true,
        gym: true,
        kitchen: true,
        wifi: true,
        heating: true,
        cableTV: true,
        location: {
          id: 3,
          name: "Huế",
          province: "Thừa Thiên Huế",
          country: "Việt Nam",
        },
        image:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbMwKbIezzGGAk8cUr6jHmAp2HSrnKPQetjQ&usqp=CAU",
      },
      {
        id: 3,
        name: "Phòng Khách Sạn Hoa Anh Đào",
        guest: 2,
        bedRoom: 1,
        bath: 1,
        description:
          "Phòng khách sạn nhỏ xinh với view hoa anh đào, tiện nghi hiện đại và dịch vụ chăm sóc khách hàng tận tình.",
        price: "2 000 000 VND",
        elevator: true,
        hotTub: false,
        pool: false,
        indoorFireplace: false,
        dryer: false,
        gym: false,
        kitchen: false,
        wifi: true,
        heating: true,
        cableTV: true,
        location: {
          id: 4,
          name: "Đà Nẵng",
          province: "Đà Nẵng",
          country: "Việt Nam",
        },
        image:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbMwKbIezzGGAk8cUr6jHmAp2HSrnKPQetjQ&usqp=CAU",
      },
      {
        id: 4,
        name: "Căn hộ Phố Cổ Hà Nội",
        guest: 3,
        bedRoom: 2,
        bath: 1,
        description:
          "Căn hộ trang trí theo phong cách phố cổ Hà Nội, nằm ở vị trí trung tâm và gần các điểm du lịch nổi tiếng.",
        price: "1 000 000 VND",
        elevator: false,
        hotTub: false,
        pool: false,
        indoorFireplace: false,
        dryer: true,
        gym: false,
        kitchen: true,
        wifi: true,
        heating: true,
        cableTV: true,
        location: {
          id: 5,
          name: "Hội An",
          province: "Quảng Nam",
          country: "Việt Nam",
        },
        image:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbMwKbIezzGGAk8cUr6jHmAp2HSrnKPQetjQ&usqp=CAU",
      },
      {
        id: 5,
        name: "Biệt thự Núi Hà Giang",
        guest: 6,
        bedRoom: 3,
        bath: 2,
        description:
          "Biệt thự cao cấp tại Hà Giang, có tầm nhìn tuyệt vời ra núi và không gian thoải mái, ấm áp.",
        price: "2 000 000 VND",
        elevator: false,
        hotTub: true,
        pool: false,
        indoorFireplace: true,
        dryer: true,
        gym: false,
        kitchen: true,
        wifi: true,
        heating: true,
        cableTV: true,
        location: {
          id: 6,
          name: "Sapa",
          province: "Lào Cai",
          country: "Việt Nam",
        },
        image:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbMwKbIezzGGAk8cUr6jHmAp2HSrnKPQetjQ&usqp=CAU",
      },
      {
        id: 6,
        name: "Nhà nghỉ Cồn Phú Quốc",
        guest: 4,
        bedRoom: 2,
        bath: 1,
        description:
          "Nhà nghỉ sạch sẽ và thoải mái tại đảo Phú Quốc, cách biển chỉ vài bước chân.",
        price: "1 000 000 VND",
        elevator: false,
        hotTub: false,
        pool: false,
        indoorFireplace: false,
        dryer: false,
        gym: false,
        kitchen: false,
        wifi: true,
        heating: true,
        cableTV: true,
        location: {
          id: 7,
          name: "Nha Trang",
          province: "Khánh Hòa",
          country: "Việt Nam",
        },
        image:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbMwKbIezzGGAk8cUr6jHmAp2HSrnKPQetjQ&usqp=CAU",
      },
      {
        id: 7,
        name: "Homestay Mộc Châu",
        guest: 5,
        bedRoom: 3,
        bath: 2,
        description:
          "Homestay gần khu du lịch Mộc Châu, với view đẹp và không gian yên bình, thích hợp cho các đoàn du lịch gia đình.",
        price: "800 000 VND",
        elevator: false,
        hotTub: false,
        pool: false,
        indoorFireplace: false,
        dryer: false,
        gym: false,
        kitchen: true,
        wifi: true,
        heating: true,
        cableTV: true,
        location: {
          id: 8,
          name: "Đà Lạt",
          province: "Lâm Đồng",
          country: "Việt Nam",
        },
        image:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbMwKbIezzGGAk8cUr6jHmAp2HSrnKPQetjQ&usqp=CAU",
      },
      {
        id: 8,
        name: "Căn hộ Biển Đà Nẵng",
        guest: 4,
        bedRoom: 2,
        bath: 2,
        description:
          "Căn hộ sang trọng với tầm nhìn ra biển Đà Nẵng, nội thất hiện đại và tiện nghi đẳng cấp.",
        price: "700 000 VND",
        elevator: true,
        hotTub: false,
        pool: true,
        indoorFireplace: false,
        dryer: true,
        gym: true,
        kitchen: true,
        wifi: true,
        heating: true,
        cableTV: true,
        location: {
          id: 8,
          name: "Đà Lạt",
          province: "Lâm Đồng",
          country: "Việt Nam",
        },
        image:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbMwKbIezzGGAk8cUr6jHmAp2HSrnKPQetjQ&usqp=CAU",
      },
      {
        id: 9,
        name: "Biệt thự Hồ Tuyền Lâm",
        guest: 10,
        bedRoom: 5,
        bath: 4,
        description:
          "Biệt thự cao cấp bên bờ hồ Tuyền Lâm, với không gian lớn, đầy đủ tiện nghi và view hồ tuyệt đẹp.",
        price: "900 000 VND",
        elevator: true,
        hotTub: true,
        pool: true,
        indoorFireplace: true,
        dryer: true,
        gym: true,
        kitchen: true,
        wifi: true,
        heating: true,
        cableTV: true,
        location: {
          id: 7,
          name: "Nha Trang",
          province: "Khánh Hòa",
          country: "Việt Nam",
        },
        image:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbMwKbIezzGGAk8cUr6jHmAp2HSrnKPQetjQ&usqp=CAU",
      },
      {
        id: 10,
        name: "Nhà nghỉ Lúa Mẫu Sơn",
        guest: 3,
        bedRoom: 2,
        bath: 1,
        description:
          "Nhà nghỉ nhỏ xinh tại Mẫu Sơn, với view núi và không gian yên tĩnh, lý tưởng cho kỳ nghỉ cuối tuần.",
        price: "1 000 000 VND",
        elevator: false,
        hotTub: false,
        pool: false,
        indoorFireplace: false,
        dryer: false,
        gym: false,
        kitchen: true,
        wifi: true,
        heating: true,
        cableTV: true,
        location: {
          id: 6,
          name: "Sapa",
          province: "Lào Cai",
          country: "Việt Nam",
        },
        image:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbMwKbIezzGGAk8cUr6jHmAp2HSrnKPQetjQ&usqp=CAU",
      },
      {
        id: 11,
        name: "Homestay Cồn Phụng",
        guest: 6,
        bedRoom: 3,
        bath: 2,
        description:
          "Homestay nằm trên một ngọn đồi tại Cồn Phụng, với không gian xanh mát và view ra biển, giúp bạn thư giãn sau những ngày làm việc căng thẳng.",
        price: "2 000 000 VND",
        elevator: false,
        hotTub: false,
        pool: false,
        indoorFireplace: false,
        dryer: false,
        gym: false,
        kitchen: true,
        wifi: true,
        heating: true,
        cableTV: true,
        location: {
          id: 5,
          name: "Hội An",
          province: "Quảng Nam",
          country: "Việt Nam",
        },
        image:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbMwKbIezzGGAk8cUr6jHmAp2HSrnKPQetjQ&usqp=CAU",
      },
      {
        id: 12,
        name: "Căn hộ Mỹ Khê Beach",
        guest: 4,
        bedRoom: 2,
        bath: 2,
        description:
          "Căn hộ hiện đại tại khu du lịch biển Mỹ Khê, gần các điểm ăn uống và giải trí phổ biến.",
        price: "3 000 000 VND",
        elevator: true,
        hotTub: false,
        pool: true,
        indoorFireplace: false,
        dryer: true,
        gym: true,
        kitchen: true,
        wifi: true,
        heating: true,
        cableTV: true,
        location: {
          id: 4,
          name: "Đà Nẵng",
          province: "Đà Nẵng",
          country: "Việt Nam",
        },
        image:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbMwKbIezzGGAk8cUr6jHmAp2HSrnKPQetjQ&usqp=CAU",
      },
      {
        id: 13,
        name: "Biệt thự Sapa Highland",
        guest: 8,
        bedRoom: 4,
        bath: 3,
        description:
          "Biệt thự cao cấp với tầm nhìn ra thung lũng Sapa, không gian rộng rãi và tiện nghi đầy đủ.",
        price: " 1 500 000 VND",
        elevator: false,
        hotTub: true,
        pool: true,
        indoorFireplace: true,
        dryer: true,
        gym: false,
        kitchen: true,
        wifi: true,
        heating: true,
        cableTV: true,
        location: {
          id: 3,
          name: "Huế",
          province: "Thừa Thiên Huế",
          country: "Việt Nam",
        },
        image:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbMwKbIezzGGAk8cUr6jHmAp2HSrnKPQetjQ&usqp=CAU",
      },
      {
        id: 14,
        name: "Homestay Đại Lải",
        guest: 5,
        bedRoom: 3,
        bath: 2,
        description:
          "Homestay nằm bên bờ hồ Đại Lải, với không gian yên tĩnh và view đẹp, phù hợp cho kỳ nghỉ cuối tuần cùng gia đình hoặc bạn bè.",
        price: " 1 800 000 VND",
        elevator: false,
        hotTub: false,
        pool: false,
        indoorFireplace: false,
        dryer: false,
        gym: false,
        kitchen: true,
        wifi: true,
        heating: true,
        cableTV: true,
        location: {
          id: 2,
          name: "Hạ Long",
          province: "Quảng Ninh",
          country: "Việt Nam",
        },
        image:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbMwKbIezzGGAk8cUr6jHmAp2HSrnKPQetjQ&usqp=CAU",
      },
    ],

    roomListTemp: [],
    roomDetail: {},
  }),
  mutations: {
    getRoomByLocationMutation(state, payload) {
      state.roomListTemp = state.roomList.filter(
        (room) => room.location.id == payload
      );
    },

    setRoomDetailMutaion(state, payload) {
      state.roomDetail = state.roomList.find((room) => room.id == payload);
    },
  },
  actions: {
    getRoomByLocationAction(context, payload) {
      context.commit("getRoomByLocationMutation", payload);
    },

    getRoomDetailAction(context, payload) {
      console.log("ID1: ", payload);
      context.commit("setRoomDetailMutaion", payload);
    },
  },
  getters: {},
};

export default moduleRoom;
